on: workflow_dispatch

jobs:
  show-python-version:
    name: Show Python Version
    runs-on: ubuntu-latest
    steps:
      - run: python --version

  specify-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: python --version
